name: logincompleto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

dev_dependencies:
  animate_do: ^3.3.4
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/login/
    - assets/images/welcome/
    - assets/images/register/
    - assets/images/securitycheckup/
